myfile=open("hello.txt","w")
myfile.write("ICTA CALICUT FULL STACK")
myfile.close()
print("file created succesfully")
myfile2=open("hello.txt","r")
print("file read successfully")
s=myfile.read()
print(s)
myfile2.close()
